### Topics

GET http://localhost:8080/topics HTTP/1.1

### Elements

GET http://localhost:8080/elements/meals_elements HTTP/1.1

###

POST http://localhost:8080/elements/meals_elements HTTP/1.1
content-type: application/json

{
    "data": [{"name": "rice"},{"name": "egg"},{"name": "cucumber"}]
}

### Entries

GET http://localhost:8080/entries/meals_entries HTTP/1.1

###

POST http://localhost:8080/entries/meals_entries HTTP/1.1
content-type: application/json

{
    "data": {
        "elements": [{"name":"rice","id":"xyz"},{"name":"soy sauce","create":true}],
        "note": "note content",
        "date": "2021-12-12T13:26:07.016Z"
    }
}